package assets.elements.vehicles;

import assets.Startable;
import assets.elements.Vehicle;
import assets.elements.vehicles.engines.Engine;

import java.awt.*;

/**
 * A Car is a Vehicle with a door count and a single Engine.
 * The power generated by the Engine is used to increase the speed of the car.
 */
public abstract class motorVehicles extends Vehicle implements Startable {
    private final int nrDoors; // Number of doors on the car

    private Engine engine;
    private boolean started;


    /**
     * @param nrDoors number of doors of the car
     * @param engine engine of the car
     * @param modelName the name of the model
     * @param color the initial color of the car
     * @param height the height of the car
     * @param weight the bare weight of the car, without any engine
     */
    public motorVehicles(int nrDoors, Engine engine, String modelName, Color color, double height, double weight){
        super(modelName, color, height, weight);
        this.nrDoors = nrDoors;
        this.engine = engine;
        stop();
    }

    /**
     * @return number of doors
     */
    public int getNrDoors(){
        return nrDoors;
    }

    /**
     * Start the engine of the car, it will be possible to use {@link #gas} and {@link #brake}
     */
    public void start(){
        started = true;
        engine.start();
    }

    /**
     * Stop the engine of the car
     */
    public void stop(){
        started = false;
        engine.stop();
    }

    /**
     * @return true if the car is started, false otherwise
     */
    public boolean isStarted(){
        return started;
    }

    private void incrementSpeed(double amount){
        double newSpeed = Math.min(getSpeed() + engine.getGeneratedPower() * amount, engine.getMaxEnginePower());
        if (newSpeed > getSpeed()) setSpeed(newSpeed);
    }

    private void decrementSpeed(double amount){
        double newSpeed = Math.max(getSpeed() - engine.getGeneratedPower() * amount,0);
        if (newSpeed < getSpeed()) setSpeed(newSpeed);
    }

    /**
     * The gas method is used to increase the speed of the car
     * @param amount between 0 and 1
     */
    public void gas(double amount){
        if (!isStarted()){
            System.out.println("Car must be started to use gas!");
            return;
        }
        if (amount < 0 || amount > 1) {
            System.out.println("Gas amount must be double in range [0,1]");
            return;
        }
        incrementSpeed(amount);
    }

    /**
     * The brake method is used to decrease the speed of the car
     * @param amount between 0 and 1
     */
    public void brake(double amount) {
        if (amount < 0 || amount > 1) {
            System.out.println("Brake amount must be double in range [0,1]");
            return;
        }
        decrementSpeed(amount);
    }

    /**
     * @return the engine of the car
     */
    public Engine getEngine() {
        return engine;
    }

    /**
     * Change the engine of the car
     * @param engine the new engine
     */
    public void setEngine(Engine engine){
        this.engine = engine;
    }

    /**
     * Get the total weight of the car, including engine weight
     * @return the total weight
     */
    @Override
    public double getWeight() {
        return super.getWeight() + engine.getWeight();
    }
}
